[env:nanorp2040connect]
platform = raspberrypi@1.11.0
board = nanorp2040connect
framework = arduino

monitor_speed = 115200

build_flags =
    -DWS_TX_BUFFER_SIZE=256

lib_deps =
    milesburton/DallasTemperature
    paulstoffregen/OneWire
    arduino-libraries/WiFiNINA
    arduino-libraries/ArduinoHttpClient
    https://github.com/DFRobot/DFRobot_LWLP.git
