[env:nanorp2040connect]
platform = raspberrypi
board = nanorp2040connect
framework = arduino

monitor_speed = 115200

build_flags =
    -DWS_TX_BUFFER_SIZE=256

lib_deps =
    milesburton/DallasTemperature
    paulstoffregen/OneWire
    arduino-libraries/WiFiNINA
    arduino-libraries/ArduinoHttpClient