[env:nanoesp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

monitor_speed = 115200

build_flags =
    -DWS_TX_BUFFER_SIZE=256

lib_deps =
    milesburton/DallasTemperature
    paulstoffregen/OneWire
    arduino-libraries/ArduinoHttpClient