#pragma once

// Self-contained page: deliberately no CDN, fonts, analytics, or framework.
static const char CONFIG_PAGE[] = R"HTML(<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>FermentationSensor</title><style>
body{font:15px system-ui;margin:auto;max-width:760px;padding:16px;background:#f4f6f5;color:#183029}fieldset{border:0;background:white;margin:12px 0;padding:16px;border-radius:8px}label{display:grid;grid-template-columns:1fr 12em;gap:8px;margin:8px}input{padding:7px}button{padding:10px;margin:5px}small{color:#a33}#status{padding:10px} @media(max-width:540px){label{grid-template-columns:1fr}}
</style></head><body><h1>FermentationSensor</h1><fieldset><legend>Gerät</legend><label>Name<input id="deviceName" maxlength="63"></label><p>UUID: <code id="deviceId"></code></p><p>IP-Adresse: <code id="ip"></code></p></fieldset>
<form id="form"><fieldset><legend>Diagnose</legend><label>Ereignisdiagnose<input type="checkbox" id="events"></label><label>Pressure Rohdaten 10 Hz<input type="checkbox" id="rawPressure"></label><small>Nur zur Diagnose. Erzeugt sehr viele serielle Ausgaben.</small></fieldset>
<fieldset><legend>Druckmessung</legend><div id="pressure"></div></fieldset><fieldset><legend>Aggregation</legend><label>Fensterdauer (ms)<input type="number" id="windowMs"></label></fieldset><fieldset><legend>Temperatur</legend><label>Änderungsschwelle (°C)<input type="number" step="any" id="sendDeltaC"></label></fieldset>
<button>Speichern</button><button type="button" id="reload">Werte neu laden</button><button type="button" id="defaults">Defaults anzeigen/zurücksetzen</button></form><div id="status"></div><script>
const fields={sampleIntervalMs:'Sampling Intervall (ms)',calibrationMs:'Kalibrierungsdauer (ms)',minTriggerDeltaPa:'Mindest-Trigger (Pa)',noiseFactor:'Noise Factor',releaseFactor:'Release Factor',minDurationMs:'Min. Bubble-Dauer (ms)',maxDurationMs:'Max. Bubble-Dauer (ms)',refractoryMs:'Refractory (ms)',baselineTrackingAlpha:'Baseline Tracking Alpha'};for(const [id,n] of Object.entries(fields))pressure.insertAdjacentHTML('beforeend',`<label>${n}<input type="number" step="any" id="${id}"></label>`);
const defaults={version:1,diagnostics:{events:true,rawPressure:false},pressure:{sampleIntervalMs:100,calibrationMs:300000,minTriggerDeltaPa:.5,noiseFactor:5,releaseFactor:.4,minDurationMs:100,maxDurationMs:3000,refractoryMs:500,baselineTrackingAlpha:.001},aggregation:{windowMs:60000},temperature:{sendDeltaC:1}};
function fill(c){events.checked=c.diagnostics.events;rawPressure.checked=c.diagnostics.rawPressure;for(const k in fields)document.getElementById(k).value=c.pressure[k];windowMs.value=c.aggregation.windowMs;sendDeltaC.value=c.temperature.sendDeltaC}function payload(){let p={};for(const k in fields)p[k]=Number(document.getElementById(k).value);return{version:1,diagnostics:{events:events.checked,rawPressure:rawPressure.checked},pressure:p,aggregation:{windowMs:Number(windowMs.value)},temperature:{sendDeltaC:Number(sendDeltaC.value)}}}async function load(){try{fill(await(await fetch('/api/config')).json());let d=await(await fetch('/api/device')).json();deviceId.textContent=d.deviceId;deviceName.value=d.deviceName;ip.textContent=location.hostname}catch(e){status.textContent='Fehler: '+e}}reload.onclick=load;defaults.onclick=()=>fill(defaults);form.onsubmit=async e=>{e.preventDefault();status.textContent='Speichere…';try{let r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});let t=await r.text();if(!r.ok)throw Error(t);let n=await fetch('/api/device/name',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:deviceName.value})});let u=await n.text();if(!n.ok)throw Error(u);status.textContent='Erfolgreich gespeichert.'}catch(e){status.textContent='Fehler: '+e.message}};load();
</script></body></html>)HTML";
