#pragma once

// Self-contained page: deliberately no CDN, fonts, analytics, or framework.
static const char CONFIG_PAGE[] = R"HTML(<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>FermentationSensor</title><style>
body{font:15px system-ui;margin:auto;max-width:760px;padding:16px;background:#f4f6f5;color:#183029}fieldset{border:0;background:white;margin:12px 0;padding:16px;border-radius:8px}label{display:grid;grid-template-columns:1fr 12em;gap:8px;margin:8px}input{padding:7px}button{padding:10px;margin:5px}small{color:#a33}.statusgrid{display:grid;grid-template-columns:11em 1fr;gap:7px 12px}.statusgrid code{overflow-wrap:anywhere}.ok{color:#176b42;font-weight:600}.bad{color:#a33;font-weight:600}.muted{color:#66736e}#errors{margin-top:12px;padding:10px;border-radius:6px;background:#f4f6f5}#errors.bad{background:#fff1f1}#saveStatus{padding:10px}@media(max-width:540px){label{grid-template-columns:1fr}.statusgrid{grid-template-columns:1fr}}
</style></head><body><h1>FermentationSensor</h1><fieldset><legend>Gerät</legend><label>Name<input id="deviceName" maxlength="63"></label><p>UUID: <code id="deviceId"></code></p><p>IP-Adresse: <code id="ip"></code></p></fieldset>
<fieldset><legend>Live-Status</legend><div class="statusgrid"><span>Messung</span><strong id="measurementState">–</strong><span>Backend</span><strong id="backendState">–</strong><span>Bier-Zuordnung</span><code id="assignedBeerId">–</code><span>WLAN</span><span id="wifiState">–</span><span>Temperatursensoren</span><strong id="temperatureState">–</strong><span>Außen-ID</span><code id="ambientSensorId">–</code><span>Bier-ID</span><code id="beerSensorId">–</code><span>Temperaturen</span><span id="temperatureValues">–</span><span>Drucksensor (I²C 0x00)</span><strong id="pressureState">–</strong><span>Druck</span><span id="pressureValue">–</span></div><div id="errors" class="muted">Status wird geladen…</div><button type="button" id="statusReload">Status aktualisieren</button><small id="statusUpdated"></small></fieldset>
<form id="form"><fieldset><legend>Diagnose</legend><label>Ereignisdiagnose<input type="checkbox" id="events"></label><label>Pressure Rohdaten 10 Hz<input type="checkbox" id="rawPressure"></label><small>Nur zur Diagnose. Erzeugt sehr viele serielle Ausgaben.</small></fieldset>
<fieldset><legend>Druckmessung</legend><div id="pressure"></div></fieldset><fieldset><legend>Aggregation</legend><label>Fensterdauer (ms)<input type="number" id="windowMs"></label></fieldset><fieldset><legend>Temperatur</legend><label>Änderungsschwelle (°C)<input type="number" step="any" id="sendDeltaC"></label></fieldset>
<button>Speichern</button><button type="button" id="reload">Werte neu laden</button><button type="button" id="defaults">Defaults anzeigen/zurücksetzen</button></form><div id="saveStatus"></div><script>
const fields={sampleIntervalMs:'Sampling Intervall (ms)',calibrationMs:'Kalibrierungsdauer (ms)',minTriggerDeltaPa:'Mindest-Trigger (Pa)',noiseFactor:'Noise Factor',releaseFactor:'Release Factor',minDurationMs:'Min. Bubble-Dauer (ms)',maxDurationMs:'Max. Bubble-Dauer (ms)',refractoryMs:'Refractory (ms)',baselineTrackingAlpha:'Baseline Tracking Alpha'};for(const [id,n] of Object.entries(fields))pressure.insertAdjacentHTML('beforeend',`<label>${n}<input type="number" step="any" id="${id}"></label>`);
const defaults={version:1,diagnostics:{events:true,rawPressure:false},pressure:{sampleIntervalMs:100,calibrationMs:300000,minTriggerDeltaPa:.5,noiseFactor:5,releaseFactor:.4,minDurationMs:100,maxDurationMs:3000,refractoryMs:500,baselineTrackingAlpha:.001},aggregation:{windowMs:60000},temperature:{sendDeltaC:1}};
function fill(c){events.checked=c.diagnostics.events;rawPressure.checked=c.diagnostics.rawPressure;for(const k in fields)document.getElementById(k).value=c.pressure[k];windowMs.value=c.aggregation.windowMs;sendDeltaC.value=c.temperature.sendDeltaC}function payload(){let p={};for(const k in fields)p[k]=Number(document.getElementById(k).value);return{version:1,diagnostics:{events:events.checked,rawPressure:rawPressure.checked},pressure:p,aggregation:{windowMs:Number(windowMs.value)},temperature:{sendDeltaC:Number(sendDeltaC.value)}}}
function health(el,good,text){el.textContent=text;el.className=good?'ok':'bad'}
async function loadStatus(){try{let r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw Error(await r.text());let s=await r.json();measurementState.textContent=s.measurementState;health(backendState,s.gateway.connected&&s.gateway.registered,s.gateway.registered?'verbunden / registriert':s.gateway.connected?'verbunden / nicht registriert':'getrennt');assignedBeerId.textContent=s.gateway.beerId||'–';wifiState.textContent=s.wifi.rssi+' dBm';ambientSensorId.textContent=s.temperature.ambientId||'nicht konfiguriert';beerSensorId.textContent=s.temperature.beerId||'nicht konfiguriert';let tempWaiting=!s.temperature.attempted;health(temperatureState,tempWaiting||s.temperature.ready,tempWaiting?'wartet auf Messung':s.temperature.ready?'OK':'FEHLER');temperatureValues.textContent=s.temperature.ready?`${s.temperature.ambientC.toFixed(2)} °C außen / ${s.temperature.beerC.toFixed(2)} °C Bier`:'–';let pressureWaiting=s.pressure.available&&!s.pressure.attempted;health(pressureState,pressureWaiting||s.pressure.ready,pressureWaiting?'wartet auf Messung':s.pressure.ready?'OK':s.pressure.error||'FEHLER');pressureValue.textContent=s.pressure.ready?s.pressure.pa.toFixed(2)+' Pa':'–';if(s.errors.length){errors.className='bad';errors.textContent='Fehler: '+s.errors.join(' · ')}else{errors.className='ok';errors.textContent='Keine Sensorfehler erkannt.'}statusUpdated.textContent='Stand: '+new Date().toLocaleTimeString()}catch(e){errors.className='bad';errors.textContent='Status konnte nicht geladen werden: '+e.message}}
async function load(){try{fill(await(await fetch('/api/config')).json());let d=await(await fetch('/api/device')).json();deviceId.textContent=d.deviceId;deviceName.value=d.deviceName;ip.textContent=location.hostname;await loadStatus()}catch(e){saveStatus.textContent='Fehler: '+e}}reload.onclick=load;statusReload.onclick=loadStatus;defaults.onclick=()=>fill(defaults);form.onsubmit=async e=>{e.preventDefault();saveStatus.textContent='Speichere…';try{let r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});let t=await r.text();if(!r.ok)throw Error(t);let n=await fetch('/api/device/name',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:deviceName.value})});let u=await n.text();if(!n.ok)throw Error(u);saveStatus.textContent='Erfolgreich gespeichert.'}catch(e){saveStatus.textContent='Fehler: '+e.message}};load();setInterval(loadStatus,5000);
</script></body></html>)HTML";
